# -*- mode: ruby -*-
# vi: set ft=ruby :
TIME = Time.now.strftime("%Y%m%d%H%M%S")
# default the python version (python = python2 on Ubuntu 18.04)
PYTHON = ENV['PYTHON'] == 'python3' ? "python3" : "python"

Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-18.04"

  # global mounts
  config.vm.synced_folder './roots/salt/', '/srv/salt'
  config.vm.synced_folder './roots/pillar', '/srv/pillar'

  # global configuration
  config.vm.hostname = "docker-nginx-node.dev"
  config.vm.provider("virtualbox") { |vbox| vbox.name = "docker_nginx_node_#{TIME}" }
  config.vm.network "forwarded_port", guest: 8081, host: 8081

  # download/install salt on guest
  config.vm.provision :salt do |salt|
    salt.run_highstate = false
    salt.bootstrap_options = "-x #{PYTHON}" if PYTHON == 'python3'
  end

  # run local states seperately to workaround pip modules not reloading
  %w(docker docker_nginx).each do |state|
    config.vm.provision "shell", inline: "salt-call --local state.sls #{state}"
  end
end
