# -*- mode: ruby -*-
# vi: set ft=ruby :
TIME = Time.now.strftime("%Y%m%d%H%M%S")
# debug defaults to false
SALT_DEBUG = ENV['SALT_DEBUG'] =~ /t(rue)?|1|y(es)?/i ? true : false
# default the python version (python = python2 on Ubuntu 18.04)
PYTHON = ENV['PYTHON'] == 'python3' ? "python3" : "python"

Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-18.04"

  # global mounts
  config.vm.synced_folder './roots/salt/', '/srv/salt'
  config.vm.synced_folder './roots/pillar', '/srv/pillar'

  # global configuration
  config.vm.hostname = "nginx-node.dev"
  config.vm.provider("virtualbox") { |vbox| vbox.name = "nginx_node_#{TIME}" }
  config.vm.network "forwarded_port", guest: 80, host: 8080

  # packages needed for gitfs support
  config.vm.provision :shell, inline: 
    "apt-get -qq update && \
     apt-get -y install git-core #{PYTHON}-pygit2 #{PYTHON}-git"

  config.vm.provision :salt do |salt|
    # Workaround for permissions issues
    salt.minion_config = "./config/minion.yaml"
    salt.masterless = true
    salt.run_highstate = true
    salt.verbose = SALT_DEBUG
    salt.bootstrap_options = "-x #{PYTHON}" if PYTHON == 'python3'
  end
end
